config/routes.rb
Rails.application.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do
    root 'pages#index'
    get "work" => "pages#work", as: :work
    get "work/:id" => "pages#show_work", as: :show_work
    get "about" => "pages#about", as: :about
    get "casting" => "pages#casting", as: :casting
    get "casting/women" => "pages#show_casting", as: :casting_women, defaults: {type: 0}
    get "casting/men" => "pages#show_casting", as: :casting_men, defaults: {type: 1}
    get "casting/kids" => "pages#show_casting", as: :casting_kids, defaults: {type: 2}
    get "locations" => "pages#locations", as: :locations
    get "locations/:id" => "pages#show_location", as: :show_location
    get "clients" => "pages#clients", as: :clients
    match "get_skins" => "pages#get_skins", :format => :json, via: [:get,:post]
    match "get_skin" => "pages#get_skin", :format => :json, via: [:get,:post]
    match "get_locations" => "pages#get_locations", :format => :json, via: [:get,:post]
    match "get_about_info" => "pages#get_about_info", :format => :json, via: [:get,:post]
    match "get_casting" => "pages#get_casting", :format => :json, via: [:get,:post]
  end

  root to: redirect(:status => 302) {|_, request|
    finded_locale = request.env['HTTP_ACCEPT_LANGUAGE'] ? request.env['HTTP_ACCEPT_LANGUAGE'].scan(/\A([a-z]{2})/).first.first.to_sym : nil
    I18n.available_locales.include?(finded_locale) ? finded_locale : I18n.default_locale
  }, as: :redirected_root

end

app/views/shared/_header.haml
%header
	%a.logo{:href => "#", data: {url: root_path}}
	%nav.mb_des
		%a.item{:href => "#", class: active?(:work), data: {url: work_path}}
			%span.title= t "header.work"
		%a.item{:href => "#", class: active?(:about), data: {url: about_path}}
			%span.title= t "header.about"
		%a.item{:href => "#", class: active?(:casting), data: {url: casting_path}}
			%span.title= t "header.casting"
		%a.item{:href => "#", class: active?(:locations), data: {url: locations_path}}
			%span.title= t "header.locations"
		%a.item{:href => "#", class: active?(:clients), data: {url: clients_path}}
			%span.title= t "header.clients"
	.burger.mb_ad
	.mob_nav.mb_ad
		%nav.mb_ad
			%a.item{:href => "#", class: active?(:work), data: {url: work_path}}
				%span.title= t "header.work"
			%a.item{:href => "#", class: active?(:about), data: {url: about_path}}
				%span.title= t "header.about"
			%a.item{:href => "#", class: active?(:casting), data: {url: casting_path}}
				%span.title= t "header.casting"
			%a.item{:href => "#", class: active?(:locations), data: {url: locations_path}}
				%span.title= t "header.locations"
			%a.item{:href => "#", class: active?(:clients), data: {url: clients_path}}
				%span.title= t "header.clients"
	.add_info
		= lang_switcher
		.contacts
			=link_to t("header.mail"), "#", target: "_blank"
			=link_to t("header.facebook"), "#", target: "_blank"
			=link_to t("header.vimeo"), "#", target: "_blank"

app/views/shared/_noise.haml
.pic_noise_block
	.noise.noise1
	.noise.noise2
	.noise.noise3
	.noise.noise4
	.noise.noise5

app/views/shared/_page_about.haml
.ppls_main
	.mob_about_info_btn.mb_ad info
	.ppl_pop_up.mb_des
	.ppl_pop_up_mob.mb_ad
	=image_tag 'about/text_about.png', class: 'title_about'
	.ppls_grad
	.ppls_wrap.ppls_slider
		- about_users.each do |user|
			.ppl{class: (user.eql? user_first) ? "front" : "", data: {id: user.id}}
				.ppl_block
					= image_tag user.picture.little, class: 'ppl_img', data: {big: image_url(user.picture), small: image_url(user.picture.little)}
	.ppls_wrap.ppls_names
		- about_users.each do |user|
			.ppl{class: (user.eql? user_first) ? "front" : ""}
				.ppl_name
					%div= user.first_name
					.srname= user.last_name
	.about_footer.mb_des
		.text= about_main.describe.html_safe
		.about_r_block.table
			.td
				=image_tag 'about/R.png', class: 'r'
			.td
				.r_text= about_main.adress.html_safe
				.r_bottom
					=link_to "enquiries", about_main.enquiries, target: "_blank"
					=link_to "bidding requests", about_main.bidding, target: "_blank"
					=link_to "facebook", about_main.facebook, target: "_blank"
					=link_to "vimeo", about_main.vimeo, target: "_blank"
	.mob_about_info
		.about_footer
			.text= about_main.describe.html_safe
			.about_r_block.table
				.td
					=image_tag 'about/R.png', class: 'r'
				.td
					.r_text= about_main.adress.html_safe
					.r_bottom
						=link_to "enquiries", about_main.enquiries, target: "_blank"
						=link_to "bidding requests", about_main.bidding, target: "_blank"
						=link_to "facebook", about_main.facebook, target: "_blank"
						=link_to "vimeo", about_main.vimeo, target: "_blank"

app/views/shared/_page_casting.haml
.casting_wrap
	%svg.casting_svg{:xmlns => "http://www.w3.org/2000/svg", "xmlns:xlink" => "http://www.w3.org/1999/xlink", width: "100%", height: "100%", preserveAspectRatio: "xMidYMax", viewBox: "0 0 1920 1080"}
		%defs
			/ %pattern#cast_grad{x:0, y:0, width: "4", height: "500",patternUnits: "userSpaceOnUse"}
			/ 	%image{x:0, y:0, width: "4", height: "500", "xlink:href" => image_url('casting/gradient.png')}
			%lineargradient#cast_grad{x1: "0%", x2: "0%", y1: "0%", y2: "100%"}
				%stop{offset: "0%", style: "stop-color:rgb(7,3,26);stop-opacity:0"}
				%stop{offset: "12%", style: "stop-color:rgb(7,3,26);stop-opacity:0.1"}
				%stop{offset: "50%", style: "stop-color:rgb(7,3,26);stop-opacity:1"}
		%image.cast_man{transform:"matrix(1, 0, 0, 1, 0, 1071)", x:473, y:9, width: "663", height: "1071", "xlink:href" => image_url('casting/man.png')}
		%image.cast_woman{transform:"matrix(1, 0, 0, 1, 0, 892)", x:277, y:188, width: "591", height: "892", "xlink:href" => image_url('casting/woman.png')}
		%image.cast_boy{transform:"matrix(1, 0, 0, 1, 0, 945)", x:955, y:135, width: "716", height: "945", "xlink:href" => image_url('casting/boy.png')}
		%image.cast_girl{transform:"matrix(1, 0, 0, 1, 0, 770)", x:797, y:310, width: "601", height: "770", "xlink:href" => image_url('casting/girl.png')}
		%rect.svg_grad{transform:"matrix(1, 0, 0, 1, 0, 0)", x:"-50%", y:580, width: "200%", height: "500", fill:"url(#cast_grad)"}
		%g.cast_title.cast_title_l{transform:"matrix(1, 0, 0, 1, 2603, 587)"}
			%path{fill:"#00aeef", d: "M11 31 L686 0 L773 147 L702 277 L0 272 z"}
			%image.t_star{x:60, y:55, width: "616", height: "181", "xlink:href" => image_url('casting/t_waggon.png')}
		%g.cast_title.cast_title_r{transform:"matrix(1, 0, 0, 1, -1455, 591)"}
			%path{fill:"#f17c45", d: "M0 0 L491 45 L472 256 L47 282 z"}
			%image.t_star{x:60, y:55, width: "366", height: "181", "xlink:href" => image_url('casting/t_star.png')}
		%image.cast_girl.cast_girl_fingers{opacity:0, transform:"matrix(1, 0, 0, 1, 0, 770)", x:797, y:310, width: "601", height: "770", "xlink:href" => image_url('casting/girl_fingers.png')}
		%text.cast_text.cast_cat_man{transform:"matrix(1, 0, 0, 1, 0, -800)", x: 440, y: 180, opacity: 0, data: {type: 0, url: casting_women_path}} WOMEN
		%text.cast_text.cast_cat_woman{transform:"matrix(1, 0, 0, 1, 0, -800)", x: 980, y: 180, opacity: 0, data: {type: 1, url: casting_men_path}} MEN
		%text.cast_text.cast_cat_kids{transform:"matrix(1, 0, 0, 1, 0, -800)", x: 1360, y: 180, opacity: 0, data: {type: 2, url: casting_kids_path}} KIDS

	.cast_bot_text.mb_des= casting_main.describe
	.mob_info_btn.mob_casting_info_btn.mb_ad info
	.mob_info.mob_casting_info.mb_ad
		.about_footer
			.text= casting_main.describe
	.cast_gal
		- if @casting_pictures
			= render partial: "shared/casting/casting", locals: {type: @casting_type, pictures: @casting_pictures}

app/views/shared/_page_clients.haml
.cl_content
	.bg
	.girl
	%h1{:class => 'top'} 
		TOP 
		%span 
			C
			%a 
				LIE
			NTS
	.gradient
	.logos
		.wrapper{:style => "width: #{client_logos.length * 29 * 2}rem;"}
			- client_logos.each do |logo|
				.client
					%figure{:style => "background-image: url(#{logo.picture.url})"}
			- client_logos.each do |logo|
				.client
					%figure{:style => "background-image: url(#{logo.picture.url})"}

	.bottom.mb_des
		.left.side
		.center
			%h1= client_main.footer.html_safe
		.right.side

	.mob_info_btn.mob_clients_info_btn.mb_ad info
	.mob_info.mob_clients_info.mb_ad
		.about_footer
			.bottom
				.center
					%h1= client_main.footer.html_safe
				.left.side
				.right.side

app/views/shared/_page_home.haml
.citys
	.city.city_top
	.city.city_bottom
.inside_block
	.logo_big
	.bot_block.clearfix
		.bb
			.text
				= image_tag "mp_t1.png"
		.bb
			.text
				= image_tag "mp_t2.png"
		.bb
			.text
				= image_tag "mp_t3.png"
.home_perspective
	.cloud.cloud1
	.cloud.cloud2
	.cloud.cloud3
	.cloud.cloud4
	.cloud.cloud5
	.cloud.cloud6
	.cloud.cloud7
	.cloud.cloud8
	.cloud.cloud9
	.cloud.cloud10
	.cloud.cloud11

app/views/shared/_page_locations.haml
%svg.loc_svg{:xmlns => "http://www.w3.org/2000/svg", "xmlns:xlink" => "http://www.w3.org/1999/xlink", width: "100%", height: "100%", preserveAspectRatio: "xMidYMid", viewBox: "0 0 2700 1340"}
	%image{x:0, y:0, width: "2700", height: "1340", "xlink:href" => image_url('loc_bridge.jpg')}
	%image.loc_text3{x:85, y:772, width: "2530", :height => "568", "xlink:href" => image_url('loc_bridge_broken.png'), opacity: "0"}
	%image.loc_text4.loc_stone1{transform: "matrix(0.2, 0, 0, 0.2, 1100, 900)", x:223, y:828, width: "2253", height: "632", "xlink:href" => image_url('loc_stones1.png'), opacity: "0"}
	%image.loc_text4.loc_stone2{transform: "matrix(0.2, 0, 0, 0.2, 1100, 900)", x:223, y:828, width: "2253", height: "632", "xlink:href" => image_url('loc_stones2.png'), opacity: "0"}
	%image.loc_text4.loc_stone3{transform: "matrix(0.2, 0, 0, 0.2, 1100, 900)", x:223, y:828, width: "2253", height: "632", "xlink:href" => image_url('loc_stones3.png'), opacity: "0"}
	%image.loc_text2{ transform: "matrix(1, 0, 0, 1, 0, -100)", opacity:"0", x: "382", y: "730", width: "1935", height: "256", "xlink:href" => image_url('loc_final_shadow.png')}
	%image.loc_text{ transform: "matrix(1, 0, 0, 1, 0, -1200)", x: "382", y: "720", width: "1935", height: "256", "xlink:href" => image_url('loc_final.png')}
	%image.loc_text5{ transform: "matrix(1, 0, 0, 1, 0, 0)", opacity: '0', x: "382", y: "720", width: "1898", height: "444", "xlink:href" => image_url('smoke.png')}
.loc_footer.mb_des= location_main.describe
.loc_nav
	- locations.each_with_index do |location, index|
		.loc_nav_item
			=link_to "#", class: "loc_nav_size#{index%10+1}", data: {id: location.id, url: show_location_path(locale, location)} do
				%span= location.name

.mob_info_btn.mib_w.mob_location_info_btn.mb_ad info
.mob_info.mob_location_info.mb_ad
	.about_footer
		.text= location_main.describe

.loc_cats
	.loc_cat
		.work_block

app/views/shared/_page_work.haml
.mob_wb_categ.mb_ad
	.wb_menu_block
		- categories.each do |category|
			.wb_menu_item{class: (@show_work_id == category.id) ? "active" : ""}
				=link_to '#', data: {id: category.id, url:  show_work_path(locale, category.id)} do
					%span= category.name
.wb_pop_up
.wb_content
	= render partial: "shared/work/work_menu"
	.mob_wb_categ_btn.mb_ad categories
	.mob_wb_work.mb_ad
	.unhover_block
	.main_work_block.active
		= render partial: "shared/work/work_main_categ"
	.wb_cats
		.wb_cat
			.work_block