config/routes.rb
Rails.application.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do
    root 'pages#index'
    get "work" => "pages#work", as: :work
    get "work/:id" => "pages#show_work", as: :show_work
    get "about" => "pages#about", as: :about
    get "casting" => "pages#casting", as: :casting
    get "casting/women" => "pages#show_casting", as: :casting_women, defaults: {type: 0}
    get "casting/men" => "pages#show_casting", as: :casting_men, defaults: {type: 1}
    get "casting/kids" => "pages#show_casting", as: :casting_kids, defaults: {type: 2}
    get "locations" => "pages#locations", as: :locations
    get "locations/:id" => "pages#show_location", as: :show_location
    get "clients" => "pages#clients", as: :clients
    match "get_skins" => "pages#get_skins", :format => :json, via: [:get,:post]
    match "get_skin" => "pages#get_skin", :format => :json, via: [:get,:post]
    match "get_locations" => "pages#get_locations", :format => :json, via: [:get,:post]
    match "get_about_info" => "pages#get_about_info", :format => :json, via: [:get,:post]
    match "get_casting" => "pages#get_casting", :format => :json, via: [:get,:post]
  end

  root to: redirect(:status => 302) {|_, request|
    finded_locale = request.env['HTTP_ACCEPT_LANGUAGE'] ? request.env['HTTP_ACCEPT_LANGUAGE'].scan(/\A([a-z]{2})/).first.first.to_sym : nil
    I18n.available_locales.include?(finded_locale) ? finded_locale : I18n.default_locale
  }, as: :redirected_root

end

app/views/shared/work/_mob_work.haml
.wb_cont
	.categ_name
		= skin.try(:category).try(:name)
	.work_name= skin.name
	.work_info
		.add_block
			%span client
			= skin.client
		.add_block
			%span brand
			= skin.brand
		.add_block
			%span team
			= skin.try(:team).try(:director)
			= skin.try(:team).try(:operator)
		.add_block
			%span awards
			.award_blocks
				.award_block
					.text_top Short-list in category “production”
					.text_mid cinematography
					.text_bottom 2013
	.btn
		%span Watch video

app/views/shared/work/_work_content.haml
- if skin
	- url ||= "" 
	.wb_cont
		.categ_name= skin.try(:category).try(:name)
		.work_name= skin.try(:name)
		.work_info
			.add_block
				%span client
				= skin.try(:client)
			.add_block
				%span brand
				= skin.try(:brand)
			.add_block
				%span team
				= skin.try(:team).try(:director)
				= skin.try(:team).try(:operator)
			.add_block
				%span awards
				.award_blocks
					.award_block
						.text_top Short-list in category “production”
						.text_mid cinematography
						.text_bottom 2013
		.btn{class: btn_left ? "btn_left" : "" , data: {url: url}}
			%span Watch video

app/views/shared/work/_work_main_categ.haml
.wb_title
	.wb_title_text1 WORK
	.wb_title_text2 FROM
	.wb_title_text3 WALL STREET
.work_block
	.wb_main_col
		.wb_col.wb_col_big.wb_col_tl.wb_col_h3{data:{id: main_skins[0].id}}
			.border
				.center_line
			= render partial: "shared/work/work_content", locals: {btn_left: false, skin: main_skins[0], url: work_path(video: main_skins[0].id)}
			.wb_blk
				.wb_blk_box.wb_blk_box_bl
				.wb_blk_box.wb_blk_box_tr.wb_full_h
				.wb_blk_line.wb_blk_line_tr
			.pic_block
				= render partial: "shared/noise"
				.pic{style: "background-image: url(#{image_url main_skins[0].try(:picture)})"}
	.wb_main_col.z_bigger
		.wb_col.wb_col_small.wb_col_tl.wb_col_h5{data:{id: main_skins[1].id}}
			.border
			= render partial: "shared/work/work_content", locals: {btn_left: false, skin: main_skins[1], url: work_path(video: main_skins[1].id)}
			.wb_blk
				.wb_blk_box.wb_blk_box_tl.wb_full_h
			.pic_block
				= render partial: "shared/noise"
				.pic{style: "background-image: url(#{image_url main_skins[1].try(:picture)})"}
		.wb_col.wb_col_big.wb_col_br.wb_col_rh.wb_col_h3{data:{id: main_skins[2].id}}
			.border
				.center_line
			= render partial: "shared/work/work_content", locals: {btn_left: true, skin: main_skins[2], url: work_path(video: main_skins[2].id)}
			.wb_blk
				.wb_blk_box.wb_blk_box_br
				.wb_blk_box.wb_blk_box_tl.wb_full_h
			.pic_block
				= render partial: "shared/noise"
				.pic{style: "background-image: url(#{image_url main_skins[2].try(:picture)})"}
	.wb_main_col
		.wb_col.wb_col_big.wb_col_tl.wb_col_h4{data:{id: main_skins[3].id}}
			.border
				.center_line
			= render partial: "shared/work/work_content", locals: {btn_left: false, skin: main_skins[3], url: work_path(video: main_skins[3].id)}
			.wb_blk
				.wb_blk_box.wb_blk_box_bl.wb_full_h.slide
				.wb_blk_box.wb_blk_box_tr.wb_full_h.slide
			.pic_block
				= render partial: "shared/noise"
				.pic{style: "background-image: url(#{image_url main_skins[3].try(:picture)})"}

app/views/shared/work/_work_menu.haml
.wb_menu_block.mb_des
  - categories.each do |category|
    .wb_menu_item{class: (@show_work_id == category.id) ? "active" : ""}
      =link_to '#', data: {id: category.id, url:  show_work_path(locale, category.id)} do
        %span= category.name